---

  - name: get munge key for distribution to nodes
    copy: src=files/munge.key
          dest=/etc/munge/munge.key
          owner=munge
          group=munge
          mode=0400
    when: slurm_munge_key_from_nfs == False
    notify:
     - restart munge

  - name: copy the munge key from NFS
    command: cp -v {{ slurm_munge_key_nfs }} /etc/munge/munge.key creates=/etc/munge/munge.key
    when: slurm_munge_key_from_nfs == True
    notify:
     - restart munge

  - name: set permissions on the munge key from NFS
    file: path=/etc/munge/munge.key mode=0400 owner=munge group=munge
    when: slurm_munge_key_from_nfs == True
    notify:
     - restart munge

  - name: start and enable munge
    service: name=munge state=started enabled=yes
    notify:
     - restart munge

  - name: Make sure /usr/local/libexec/slurm/epilog.d exists
    file: path=/usr/local/libexec/slurm/epilog.d state=directory owner=root group=root mode=0755 recurse=yes

  - name: Create namespace epilog script
    template: src=namespace_clean.sh.j2 dest=/usr/local/libexec/slurm/epilog.d/namespace_clean.sh owner=root group=root mode=0755

  - name: start and enable slurm on EL6
    service: name=slurm state=started enabled=yes
    when: ansible_distribution_major_version == "6"
    ignore_errors: yes

  - name: start and enable slurmD on EL7
    service: name=slurmd state=started enabled=yes
    when: ansible_distribution_major_version == "7"
    ignore_errors: yes
