---

  - name: restart munge
    service: name=munge state=restarted

  - name: restart slurm
    command: /bin/true
    notify:
      - restart slurmd
      - restart slurmctld
      - restart slurmdbd
    changed_when: True

  - name: restart slurmd
    service: name={{ slurmd_service }} state=restarted
    when: "'slurm_compute' in group_names"

  - name: restart slurmctld
    service: name={{ slurmctld_service }} state=restarted
    when: "'slurm_service' in group_names"

  - name: restart slurmdbd
    service: name=slurmdbd state=restarted
    when: slurm_accounting_storage_host == ansible_hostname

  - name: Restart rsyslog
    service: name=rsyslog state=restarted

